---
image: ruby:2.4-alpine

.chatops: &chatops
  only:
    - chat
  before_script:
    - apk add --update build-base postgresql-dev
    - gem install bundler --no-ri --no-rdoc
    - bundle install --path vendor --retry 3 --deployment --without development
  cache:
    paths:
      - vendor/bundle
  script:
    - bundle exec ./bin/chatops $CI_JOB_NAME

.ruby: &ruby
  except:
    - chat
  before_script:
    - apk add --update build-base postgresql-dev
    - gem install bundler --no-ri --no-rdoc
    - ruby --version
    - gem --version
    - bundle --version
    - bundle install --path vendor --retry=3
  cache:
    paths:
      - vendor/ruby

rspec:
  <<: *ruby
  script:
    - bundle exec rake coverage
  services:
    - postgres:latest
  variables:
    # Configure the "postgres" service itself.
    POSTGRES_DB: chatops
    POSTGRES_USER: runner
    # Configure the test environment to connect to said service.
    TEST_DATABASE_HOST: postgres
    TEST_DATABASE_USER: runner
    TEST_DATABASE_NAME: chatops
    COVERAGE: 'true'

rubocop:
  <<: *ruby
  script:
    - bundle exec rubocop

explain:
  <<: *chatops

help:
  <<: *chatops

graph:
  <<: *chatops

feature:
  <<: *chatops

broadcast:
  <<: *chatops

user:
  <<: *chatops

query:
  <<: *chatops
