---
image: ruby:2.4-alpine

services:
- docker:dind

stages:
  - test
  - build

variables:
  CHATOPS_IMAGE: registry.gitlab.com/gitlab-com/chatops:latest

.chatops: &chatops
  image: $CHATOPS_IMAGE
  variables:
    GIT_STRATEGY: none
    GIT_SUBMODULE_STRATEGY: none
  only:
    - chat
  script:
    - bundle exec ruby /app/bin/chatops $CI_JOB_NAME

.ruby: &ruby
  except:
    - chat
  before_script:
    - apk add --update build-base postgresql-dev
    - gem install bundler --no-ri --no-rdoc
    - ruby --version
    - gem --version
    - bundle --version
    - bundle install --path vendor --retry=3
  cache:
    paths:
      - vendor/ruby

build:image:
  stage: build
  image: docker:git
  only:
    - master
  script:
    - ./bin/docker "${CHATOPS_IMAGE}"

rspec:
  <<: *ruby
  stage: test
  script:
    - bundle exec rake coverage
  services:
    - postgres:latest
  variables:
    # Configure the "postgres" service itself.
    POSTGRES_DB: chatops
    POSTGRES_USER: runner
    # Configure the test environment to connect to said service.
    TEST_DATABASE_HOST: postgres
    TEST_DATABASE_USER: runner
    TEST_DATABASE_NAME: chatops
    COVERAGE: 'true'

rubocop:
  <<: *ruby
  stage: test
  script:
    - bundle exec rubocop

explain:
  <<: *chatops

help:
  <<: *chatops

graph:
  <<: *chatops

feature:
  <<: *chatops

broadcast:
  <<: *chatops

user:
  <<: *chatops

query:
  <<: *chatops
