FROM ruby:2.4-alpine

COPY Gemfile .
COPY Gemfile.lock .

WORKDIR app

RUN apk add --update build-base postgresql-dev
RUN gem install bundler --no-ri --no-rdoc
RUN bundle install --path vendor --retry 3 --deployment --without development

ADD . /app/
